### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by dbolkensteyn** [platinummonkey/go-concurrency-limits#21]
Some unit test seems to be flaky.

For example, during the development of #20, a build on Travis CI failed with a SIGSEGV nil pointer dereference: https://travis-ci.org/platinummonkey/go-concurrency-limits/jobs/616279875#L589
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8220a1]
goroutine 88 [running]:
github.com/platinummonkey/go-concurrency-limits/limiter.(*lifoQueue).remove(0xc000104870, 0x1)
	/home/travis/gopath/src/github.com/platinummonkey/go-concurrency-limits/limiter/lifo_blocking.go:103 +0x391
github.com/platinummonkey/go-concurrency-limits/limiter.(*LifoBlockingLimiter).tryAcquire(0xc000104850, 0x964100, 0xc00009e010, 0x42d675, 0xc0001081c0)
	/home/travis/gopath/src/github.com/platinummonkey/go-concurrency-limits/limiter/lifo_blocking.go:239 +0x2e2
github.com/platinummonkey/go-concurrency-limits/limiter.(*LifoBlockingLimiter).Acquire(0xc000104850, 0x964100, 0xc00009e010, 0xc000112600, 0x18, 0xbcaa80)
	/home/travis/gopath/src/github.com/platinummonkey/go-concurrency-limits/limiter/lifo_blocking.go:250 +0x69
github.com/platinummonkey/go-concurrency-limits/limiter.TestLifoBlockingLimiter.func3.1(0xc0001081c0, 0xc000104850, 0xc000091340, 0xc00009e868, 0xc0000b6b80, 0xc00009e870, 0x7)
	/home/travis/gopath/src/github.com/platinummonkey/go-concurrency-limits/limiter/lifo_blocking_test.go:180 +0x8b
created by github.com/platinummonkey/go-concurrency-limits/limiter.TestLifoBlockingLimiter.func3
	/home/travis/gopath/src/github.com/platinummonkey/go-concurrency-limits/limiter/lifo_blocking_test.go:178 +0x63f
FAIL	github.com/platinummonkey/go-concurrency-limits/limiter	1.449s
```

Locally on my machine, I saw another failure:
```
--- FAIL: TestBlockingLimiter (0.51s)
    --- FAIL: TestBlockingLimiter/BlockingLimiterTimeout (0.51s)
        blocking_test.go:188:
                Error Trace:    blocking_test.go:188
                Error:          Not equal:
                                expected: 4
                                actual  : 5
                Test:           TestBlockingLimiter/BlockingLimiterTimeout
FAIL
FAIL    github.com/platinummonkey/go-concurrency-limits/limiter 2.139s
```

Moreover, running `go test -count=1 ./...` multiple times (notice the `-count=1` to skip caching) in a row results it in sometimes succeeding immediately:
```
?       github.com/platinummonkey/go-concurrency-limits/core    [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/example_blocking_limit [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/example_simple_limit   [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_streaming [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_streaming/pb      [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_unary     [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_unary/pb  [no test files]
?       github.com/platinummonkey/go-concurrency-limits/grpc    [no test files]
ok      github.com/platinummonkey/go-concurrency-limits/limit   1.081s
ok      github.com/platinummonkey/go-concurrency-limits/limit/functions 0.572s
ok      github.com/platinummonkey/go-concurrency-limits/limiter 1.234s
ok      github.com/platinummonkey/go-concurrency-limits/measurements    0.306s
?       github.com/platinummonkey/go-concurrency-limits/metric_registry/datadog [no test files]
?       github.com/platinummonkey/go-concurrency-limits/metric_registry/gometrics       [no test files]
ok      github.com/platinummonkey/go-concurrency-limits/strategy        1.208s
ok      github.com/platinummonkey/go-concurrency-limits/strategy/matchers       1.468s
```
but sometimes it seems to hang on the `limiter` package tests for at least many minutes:
```
?       github.com/platinummonkey/go-concurrency-limits/core    [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/example_blocking_limit [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/example_simple_limit   [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_streaming [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_streaming/pb      [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_unary     [no test files]
?       github.com/platinummonkey/go-concurrency-limits/examples/grpc_unary/pb  [no test files]
?       github.com/platinummonkey/go-concurrency-limits/grpc    [no test files]
ok      github.com/platinummonkey/go-concurrency-limits/limit   0.885s
ok      github.com/platinummonkey/go-concurrency-limits/limit/functions 0.628s
*** Test killed: ran too long (10m0s).
FAIL    github.com/platinummonkey/go-concurrency-limits/limiter 601.147s
ok      github.com/platinummonkey/go-concurrency-limits/measurements    0.337s
?       github.com/platinummonkey/go-concurrency-limits/metric_registry/datadog [no test files]
?       github.com/platinummonkey/go-concurrency-limits/metric_registry/gometrics       [no test files]
ok      github.com/platinummonkey/go-concurrency-limits/strategy        1.541s
ok      github.com/platinummonkey/go-concurrency-limits/strategy/matchers       1.286s
```

**Comment by dbolkensteyn** [comment]
Another one:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x68a072]

goroutine 78 [running]:
testing.tRunner.func1(0xc0001ae000)
        C:/Go/src/testing/testing.go:830 +0x399
panic(0x6d4d40, 0x980f90)
        C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/platinummonkey/go-concurrency-limits/limiter.TestLifoBlockingLimiter.func3(0xc0001ae000)
        C:/Users/Dinesh/Desktop/go-concurrency-limits/limiter/lifo_blocking_test.go:203 +0x752
testing.tRunner(0xc0001ae000, 0x742c78)
        C:/Go/src/testing/testing.go:865 +0xc7
created by testing.(*T).Run
        C:/Go/src/testing/testing.go:916 +0x361
FAIL    github.com/platinummonkey/go-concurrency-limits/limiter 2.472s
```

**Comment by platinummonkey** [comment]
thanks for reporting!
